### ISSUE TITLE
[PR] Did you unsubscribe?

### ISSUE THREAD

**Issue by cozylife** [GrahamCampbell/Laravel-Manager#13]
@GrahamCampbell - I saw in the past you usually respond quickly, and you're committing to various other repos recently. That leads me to believe that you probably unsubscribed to notifications on PRs for your repos on GitHub.

This is just a friendly reminder that about 5 days ago I sent a couple PRs to your Laravel-Manager and Laravel-DigitalOcean repos on here to bump the version to Laravel 5.7 as it's max, while still retaining the ability for people to update it on 5.5 and 5.6.

**Comment by GrahamCampbell** [comment]
Just released 4.1.0.
