### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by roldanlg** [GrahamCampbell/Laravel-Manager#20]
Hello, I have a use case where I need to download another project into a temporary folder in my project, update some files and then pull the temporal project back.
My problem is that I can't see how to achieve this using the provided documentation.
I have already set the authentication and the call to `GitHub::me()` works fine, but when I try to call `GitHub::me()->organizations()` or `GitHub::me()->show("myOrganization","TheRepo")`, always returns `Github\Exception\RuntimeException with message 'Requires authentication`.
How can I get authenticated?

**Comment by GrahamCampbell** [comment]
Feel free to drop me an email at hello@gjcampbell.co.uk if you'd like to engage with some paid consulting. Otherwise, the best place to get free help is probably to ask on some forums, rather than a bug tracker for an unrelated package.
