### ISSUE TITLE
Unable to test facade when class extends AbstractManager

### ISSUE THREAD

**Issue by brandonferens** [GrahamCampbell/Laravel-Manager#8]
Hey Graham,
I am currently attempting to write some tests revolving around Vimeo upload functionality. I am using vinkla/laravel-vimeo to accomplish this. During my tests I am attempting to mock the Vimeo facade. The VimeoManger that the facade delivers extends your AbstractManager class. The issue ultimately comes down to the fact that the Mock class expects the `__call()` method's signature to to be the same.

I have a feeling most classes that use facades don't implement that magic method, so it generally isn't a problem.

The mock class expects the signature:
`__call($method, array $args)`

whereas AbstractManager has:
`__call(string $method, array $parameters)`

Attempting to override your method within the VimeoManager doesn't work. However, simply updating your `__call()` method does. I'm curious if I can create a pull request to literally just change out the signature? I don't see how this would affect any functionality of the method.

Thanks!

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. This bug is fixed if you use `dev-master` of mockery I think. :)

**Comment by brandonferens** [comment]
Yep, that did the trick. Thanks @GrahamCampbell

**Comment by GrahamCampbell** [comment]
🚢
